(()=>{'use strict';
const $=s=>document.querySelector(s), boardEl=$('#board'), statusEl=$('#status'), scoreEl=$('#score'), topHand=$('#capturedTop'), bottomHand=$('#capturedBottom');
let current=null, rotated=false, sound=true, history=[];
const audio=()=>{if(!sound)return;try{const c=new (window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=430;g.gain.setValueAtTime(.06,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.07);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.08)}catch{}};
const buzz=()=>navigator.vibrate?.(12); const feedback=()=>{audio();buzz()};
function showScreen(game){$('#home').classList.toggle('active',!game);$('#gameScreen').classList.toggle('active',!!game);$('#homeBtn').classList.toggle('hidden',!game)}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1100)}
function modal(title,text,actions,icon='♟'){ $('#modalTitle').textContent=title;$('#modalText').textContent=text;$('#modalIcon').textContent=icon;const a=$('#modalActions');a.innerHTML='';actions.forEach((x,i)=>{const b=document.createElement('button');b.textContent=x.label;if(x.secondary)b.className='secondary';b.onclick=()=>{if(x.close!==false)$('#modal').classList.add('hidden');x.fn?.()};a.appendChild(b)});$('#modal').classList.remove('hidden')}
function saveState(){history.push(JSON.stringify(current));if(history.length>80)history.shift()}
function undo(){if(history.length<2)return toast('これ以上戻せません');history.pop();current=JSON.parse(history.pop());history.push(JSON.stringify(current));render();toast('1手戻しました')}
function start(game){rotated=false; history=[]; if(game==='reversi')initReversi();if(game==='chess')initChess();if(game==='shogi')initShogi();saveState();showScreen(true);render();}
function render(){if(!current)return;$('#gameKicker').textContent=current.type==='reversi'?'REVERSI':current.type==='chess'?'CHESS':'SHOGI';$('#gameTitle').textContent=current.type==='reversi'?'リバーシ':current.type==='chess'?'チェス':'将棋';boardEl.className='board '+current.type+'-board';boardEl.innerHTML='';topHand.innerHTML='';bottomHand.innerHTML='';if(current.type==='reversi')renderReversi();if(current.type==='chess')renderChess();if(current.type==='shogi')renderShogi();}
const RDIR=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]];
function initReversi(){let b=Array.from({length:8},()=>Array(8).fill(null));b[3][3]='w';b[4][4]='w';b[3][4]='b';b[4][3]='b';current={type:'reversi',board:b,turn:'b',passes:0,over:false,last:null}}
function rFlips(r,c,p){if(current.board[r][c])return[];let all=[];for(const[dR,dC]of RDIR){let rr=r+dR,cc=c+dC,tmp=[];while(rr>=0&&rr<8&&cc>=0&&cc<8&&current.board[rr][cc]&&current.board[rr][cc]!==p){tmp.push([rr,cc]);rr+=dR;cc+=dC}if(tmp.length&&rr>=0&&rr<8&&cc>=0&&cc<8&&current.board[rr][cc]===p)all.push(...tmp)}return all}
function rMoves(p){let a=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(rFlips(r,c,p).length)a.push([r,c]);return a}
function rPlay(r,c){if(current.over)return;const f=rFlips(r,c,current.turn);if(!f.length)return;saveState();current.board[r][c]=current.turn;f.forEach(([rr,cc])=>current.board[rr][cc]=current.turn);current.last=[r,c];current.turn=current.turn==='b'?'w':'b';current.passes=0;feedback();if(!rMoves(current.turn).length){current.passes++;current.turn=current.turn==='b'?'w':'b';if(!rMoves(current.turn).length){current.over=true;rFinish()}else toast('置ける場所がないためパス')}saveState();render()}
function rFinish(){let b=0,w=0;current.board.flat().forEach(x=>x==='b'?b++:x==='w'?w++:0);setTimeout(()=>modal('対局終了',b===w?`引き分けです（${b} - ${w}）`:`${b>w?'黒':'白'}の勝ちです（${b} - ${w}）`,[{label:'もう一度',fn:()=>start('reversi')},{label:'ホーム',secondary:true,fn:goHome}],b===w?'●':'🏆'),100)}
function renderReversi(){const moves=new Set(rMoves(current.turn).map(x=>x.join(',')));let cells=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)cells.push([r,c]);if(rotated)cells.reverse();cells.forEach(([r,c])=>{const e=document.createElement('div');e.className='cell';if(current.last?.[0]===r&&current.last?.[1]===c)e.classList.add('last-move');if(current.board[r][c])e.innerHTML=`<span class="stone ${current.board[r][c]}"></span>`;else if(moves.has(`${r},${c}`))e.innerHTML='<span class="hint-dot"></span>';e.onclick=()=>rPlay(r,c);boardEl.appendChild(e)});let b=0,w=0;current.board.flat().forEach(x=>x==='b'?b++:x==='w'?w++:0);$('#turnBadge').textContent=current.turn==='b'?'● 黒の番':'○ 白の番';statusEl.textContent='光っているマスに置けます';scoreEl.innerHTML=`<span>黒 <strong>${b}</strong></span><span>白 <strong>${w}</strong></span>`}
const CIMG={wk:'white_king.svg',wq:'white_queen.svg',wr:'white_rook.svg',wb:'white_bishop.svg',wn:'white_knight.svg',wp:'white_pawn.svg',bk:'black_king.svg',bq:'black_queen.svg',br:'black_rook.svg',bb:'black_bishop.svg',bn:'black_knight.svg',bp:'black_pawn.svg'};
function initChess(){const E=()=>Array(8).fill(null),b=Array.from({length:8},E);const back=['r','n','b','q','k','b','n','r'];for(let c=0;c<8;c++){b[0][c]='b'+back[c];b[1][c]='bp';b[6][c]='wp';b[7][c]='w'+back[c]}current={type:'chess',board:b,turn:'w',selected:null,last:null,castling:{wk:true,wq:true,bk:true,bq:true},ep:null,over:false,promotion:null}}
function inb(r,c){return r>=0&&r<8&&c>=0&&c<8}function color(p){return p?.[0]} function kind(p){return p?.[1]}
function pseudoMoves(r,c,attackOnly=false,state=current){const b=state.board,p=b[r][c];if(!p)return[];const co=color(p),k=kind(p),out=[],enemy=co==='w'?'b':'w';const add=(rr,cc)=>{if(inb(rr,cc)&&(!b[rr][cc]||color(b[rr][cc])===enemy))out.push([rr,cc])};const ray=(dr,dc)=>{let rr=r+dr,cc=c+dc;while(inb(rr,cc)){if(!b[rr][cc])out.push([rr,cc]);else{if(color(b[rr][cc])===enemy)out.push([rr,cc]);break}rr+=dr;cc+=dc}};if(k==='p'){const d=co==='w'?-1:1;if(attackOnly){for(const dc of[-1,1])if(inb(r+d,c+dc))out.push([r+d,c+dc])}else{if(inb(r+d,c)&&!b[r+d][c]){out.push([r+d,c]);const home=co==='w'?6:1;if(r===home&&!b[r+2*d][c])out.push([r+2*d,c])}for(const dc of[-1,1]){let rr=r+d,cc=c+dc;if(inb(rr,cc)&&b[rr][cc]&&color(b[rr][cc])===enemy)out.push([rr,cc]);if(state.ep&&state.ep[0]===rr&&state.ep[1]===cc)out.push([rr,cc])}}}if(k==='n')for(const [dr,dc]of[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])add(r+dr,c+dc);if(k==='b'||k==='q')for(const d of[[-1,-1],[-1,1],[1,-1],[1,1]])ray(...d);if(k==='r'||k==='q')for(const d of[[-1,0],[1,0],[0,-1],[0,1]])ray(...d);if(k==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);if(!attackOnly){const row=co==='w'?7:0;if(r===row&&c===4&&!isCheck(co,state)){const rights=state.castling;if((rights[co+'k'])&&!b[row][5]&&!b[row][6]&&!squareAttacked(row,5,enemy,state)&&!squareAttacked(row,6,enemy,state))out.push([row,6]);if((rights[co+'q'])&&!b[row][1]&&!b[row][2]&&!b[row][3]&&!squareAttacked(row,3,enemy,state)&&!squareAttacked(row,2,enemy,state))out.push([row,2])}}}return out}
function squareAttacked(r,c,by,state=current){for(let rr=0;rr<8;rr++)for(let cc=0;cc<8;cc++){const p=state.board[rr][cc];if(p&&color(p)===by&&pseudoMoves(rr,cc,true,state).some(m=>m[0]===r&&m[1]===c))return true}return false}
function isCheck(co,state=current){for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(state.board[r][c]===co+'k')return squareAttacked(r,c,co==='w'?'b':'w',state);return true}
function cloneState(){return JSON.parse(JSON.stringify(current))}
function cLegal(r,c){const co=color(current.board[r][c]);return pseudoMoves(r,c,false,current).filter(([rr,cc])=>{const s=cloneState();applyChessMove(s,r,c,rr,cc,false);return !isCheck(co,s)})}
function applyChessMove(s,r,c,rr,cc,real=true){const p=s.board[r][c],co=color(p),k=kind(p);if(k==='p'&&s.ep&&rr===s.ep[0]&&cc===s.ep[1]&&!s.board[rr][cc])s.board[r][cc]=null;if(k==='k'&&Math.abs(cc-c)===2){if(cc===6){s.board[r][5]=s.board[r][7];s.board[r][7]=null}else{s.board[r][3]=s.board[r][0];s.board[r][0]=null}}s.board[rr][cc]=p;s.board[r][c]=null;s.ep=null;if(k==='p'&&Math.abs(rr-r)===2)s.ep=[(r+rr)/2,c];if(k==='k'){s.castling[co+'k']=false;s.castling[co+'q']=false}if(k==='r'){if(r===(co==='w'?7:0)&&c===0)s.castling[co+'q']=false;if(r===(co==='w'?7:0)&&c===7)s.castling[co+'k']=false}if(real&&k==='p'&&(rr===0||rr===7))s.promotion=[rr,cc,co];}
function cTap(r,c){if(current.over||current.promotion)return;const p=current.board[r][c];if(current.selected){const [sr,sc]=current.selected,legal=cLegal(sr,sc);if(legal.some(m=>m[0]===r&&m[1]===c)){saveState();applyChessMove(current,sr,sc,r,c,true);current.last=[[sr,sc],[r,c]];current.selected=null;feedback();if(current.promotion){render();choosePromotion();return}current.turn=current.turn==='w'?'b':'w';afterChess();saveState();render();return}if(p&&color(p)===current.turn){current.selected=[r,c];render();return}current.selected=null;render();return}if(p&&color(p)===current.turn){current.selected=[r,c];render()}}
function choosePromotion(){modal('プロモーション','昇格する駒を選んでください。',[['クイーン','q'],['ルーク','r'],['ビショップ','b'],['ナイト','n']].map(([label,k])=>({label,fn:()=>{const[r,c,co]=current.promotion;current.board[r][c]=co+k;current.promotion=null;current.turn=co==='w'?'b':'w';afterChess();saveState();render()}})),'♛')}
function allChessMoves(co){let n=0;for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(color(current.board[r][c])===co)n+=cLegal(r,c).length;return n}
function afterChess(){const co=current.turn,moves=allChessMoves(co),chk=isCheck(co);if(!moves){current.over=true;setTimeout(()=>modal(chk?'チェックメイト':'ステイルメイト',chk?`${co==='w'?'黒':'白'}の勝ちです。`:'引き分けです。',[{label:'もう一度',fn:()=>start('chess')},{label:'ホーム',secondary:true,fn:goHome}],chk?'🏆':'♔'),100)}}
function renderChess(){let coords=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)coords.push([r,c]);if(rotated)coords.reverse();let legal=[];if(current.selected)legal=cLegal(...current.selected);coords.forEach(([r,c])=>{const e=document.createElement('div');e.className='cell '+(((r+c)%2)?'dark':'light');if(current.selected?.[0]===r&&current.selected?.[1]===c)e.classList.add('selected');if(current.last?.some(x=>x[0]===r&&x[1]===c))e.classList.add('last-move');const p=current.board[r][c];const lm=legal.find(x=>x[0]===r&&x[1]===c);if(lm)e.classList.add(p?'capture-hint':'move-hint');if(p===current.turn+'k'&&isCheck(current.turn))e.classList.add('check');if(p){const im=document.createElement('img');im.className='chess-piece';im.src='assets/chess/'+CIMG[p];im.alt=p;e.appendChild(im)}e.onclick=()=>cTap(r,c);boardEl.appendChild(e)});$('#turnBadge').textContent=current.turn==='w'?'♙ 白の番':'♟ 黒の番';statusEl.textContent=isCheck(current.turn)?'チェック！ 王を守ってください':current.selected?'移動先を選んでください':'駒を選んでください';scoreEl.innerHTML='<span>キャスリング・アンパッサン・プロモーション対応</span>'}
const SNAME={K:'王',R:'飛',B:'角',G:'金',S:'銀',N:'桂',L:'香',P:'歩','+R':'龍','+B':'馬','+S':'全','+N':'圭','+L':'杏','+P':'と'};
function initShogi(){const b=Array.from({length:9},()=>Array(9).fill(null));const row=['L','N','S','G','K','G','S','N','L'];for(let c=0;c<9;c++){b[0][c]={c:'w',k:row[c]};b[2][c]={c:'w',k:'P'};b[6][c]={c:'b',k:'P'};b[8][c]={c:'b',k:row[c]}}b[1][1]={c:'w',k:'R'};b[1][7]={c:'w',k:'B'};b[7][1]={c:'b',k:'B'};b[7][7]={c:'b',k:'R'};current={type:'shogi',board:b,turn:'b',selected:null,hand:{b:{},w:{}},drop:null,last:null,over:false}}
function sDirs(k,co){const f=co==='b'?-1:1, gold=[[f,-1],[f,0],[f,1],[0,-1],[0,1],[-f,0]],silver=[[f,-1],[f,0],[f,1],[-f,-1],[-f,1]],king=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]];if(k==='K')return [king,false];if(k==='G'||['+S','+N','+L','+P'].includes(k))return[gold,false];if(k==='S')return[silver,false];if(k==='N')return[[[2*f,-1],[2*f,1]],false];if(k==='P')return[[[f,0]],false];if(k==='L')return[[[f,0]],true];if(k==='R')return[[[-1,0],[1,0],[0,-1],[0,1]],true];if(k==='B')return[[[-1,-1],[-1,1],[1,-1],[1,1]],true];if(k==='+R')return[[[-1,0],[1,0],[0,-1],[0,1]],true,[[-1,-1],[-1,1],[1,-1],[1,1]]];if(k==='+B')return[[[-1,-1],[-1,1],[1,-1],[1,1]],true,[[-1,0],[1,0],[0,-1],[0,1]]];return[[],false]}
function sMoves(r,c){const p=current.board[r][c];if(!p)return[];let out=[];const[dirs,slide,extra]=sDirs(p.k,p.c);for(const[dr,dc]of dirs){let rr=r+dr,cc=c+dc;while(inbSh(rr,cc)){if(!current.board[rr][cc])out.push([rr,cc]);else{if(current.board[rr][cc].c!==p.c)out.push([rr,cc]);break}if(!slide)break;rr+=dr;cc+=dc}}if(extra)for(const[dr,dc]of extra){let rr=r+dr,cc=c+dc;if(inbSh(rr,cc)&&(!current.board[rr][cc]||current.board[rr][cc].c!==p.c))out.push([rr,cc])}return out}function inbSh(r,c){return r>=0&&r<9&&c>=0&&c<9}
function unprom(k){return k.startsWith('+')?k.slice(1):k} function promotable(k){return ['R','B','S','N','L','P'].includes(k)} function inZone(co,r){return co==='b'?r<=2:r>=6}
function mustPromote(k,co,r){if((k==='P'||k==='L')&&(co==='b'?r===0:r===8))return true;if(k==='N'&&(co==='b'?r<=1:r>=7))return true;return false}
function sTap(r,c){if(current.over)return;if(current.drop){if(canDrop(current.drop,r,c)){saveState();current.board[r][c]={c:current.turn,k:current.drop};current.hand[current.turn][current.drop]--;if(!current.hand[current.turn][current.drop])delete current.hand[current.turn][current.drop];current.drop=null;current.last=[r,c];endShogiTurn();feedback();saveState();render()}return}const p=current.board[r][c];if(current.selected){const[sr,sc]=current.selected,m=sMoves(sr,sc);if(m.some(x=>x[0]===r&&x[1]===c)){saveState();const mover=current.board[sr][sc],capt=current.board[r][c];if(capt){if(capt.k==='K'){current.board[r][c]=mover;current.board[sr][sc]=null;current.over=true;feedback();render();setTimeout(()=>modal('詰み',`${mover.c==='b'?'先手':'後手'}の勝ちです。`,[{label:'もう一度',fn:()=>start('shogi')},{label:'ホーム',secondary:true,fn:goHome}],'🏆'),100);return}const base=unprom(capt.k);current.hand[mover.c][base]=(current.hand[mover.c][base]||0)+1}current.board[r][c]=mover;current.board[sr][sc]=null;current.selected=null;current.last=[r,c];feedback();const can=promotable(mover.k)&&(inZone(mover.c,sr)||inZone(mover.c,r));if(mustPromote(mover.k,mover.c,r)){mover.k='+'+mover.k;endShogiTurn();saveState();render()}else if(can){render();modal('成りますか？',`${SNAME[mover.k]}を成ることができます。`,[{label:'成る',fn:()=>{mover.k='+'+mover.k;endShogiTurn();saveState();render()}},{label:'成らない',secondary:true,fn:()=>{endShogiTurn();saveState();render()}}],'成')}else{endShogiTurn();saveState();render()}return}if(p&&p.c===current.turn){current.selected=[r,c];render();return}current.selected=null;render();return}if(p&&p.c===current.turn){current.selected=[r,c];render()}}
function canDrop(k,r,c){if(current.board[r][c])return false;const co=current.turn;if((k==='P'||k==='L')&&(co==='b'?r===0:r===8))return false;if(k==='N'&&(co==='b'?r<=1:r>=7))return false;if(k==='P'){for(let rr=0;rr<9;rr++){const p=current.board[rr][c];if(p&&p.c===co&&p.k==='P')return false}}return true}
function endShogiTurn(){current.turn=current.turn==='b'?'w':'b'}
function handHtml(co,top=false){const h=current.hand[co],wrap=document.createDocumentFragment();Object.entries(h).forEach(([k,n])=>{const b=document.createElement('button');b.className='hand-piece'+(current.drop===k&&current.turn===co?' active':'');b.textContent=`${SNAME[k]}${n>1?'×'+n:''}`;b.onclick=()=>{if(current.turn!==co)return;current.selected=null;current.drop=current.drop===k?null:k;render()};wrap.appendChild(b)});return wrap}
function renderShogi(){let coords=[];for(let r=0;r<9;r++)for(let c=0;c<9;c++)coords.push([r,c]);if(rotated)coords.reverse();let legal=current.selected?sMoves(...current.selected):[];coords.forEach(([r,c])=>{const e=document.createElement('div');e.className='cell';if(current.selected?.[0]===r&&current.selected?.[1]===c)e.classList.add('selected');if(current.last?.[0]===r&&current.last?.[1]===c)e.classList.add('last-move');const p=current.board[r][c];if(legal.some(x=>x[0]===r&&x[1]===c))e.classList.add(p?'capture-hint':'move-hint');if(current.drop&&canDrop(current.drop,r,c))e.classList.add('move-hint');if(p){const smap={K:'king',R:'rook',B:'bishop',G:'gold',S:'silver',N:'knight',L:'lance',P:'pawn','+R':'dragon','+B':'horse','+S':'prom_silver','+N':'prom_knight','+L':'prom_lance','+P':'prom_pawn'};const im=document.createElement('img');im.className='shogi-piece';im.src=`assets/shogi/${p.c==='b'?'black':'white'}_${smap[p.k]}.png`;im.alt=SNAME[p.k];e.appendChild(im)}e.onclick=()=>sTap(r,c);boardEl.appendChild(e)});topHand.appendChild(handHtml(rotated?'b':'w'));bottomHand.appendChild(handHtml(rotated?'w':'b'));$('#turnBadge').textContent=current.turn==='b'?'▲ 先手の番':'▽ 後手の番';statusEl.textContent=current.drop?`${SNAME[current.drop]}を打つ場所を選んでください`:current.selected?'移動先を選んでください':'盤上の駒、または持ち駒を選んでください';scoreEl.innerHTML='<span>持ち駒・駒打ち・成り・二歩制限に対応</span>'}
function goHome(){current=null;history=[];showScreen(false)}
document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>start(b.dataset.game));$('#homeBtn').onclick=()=>modal('ホームへ戻りますか？','現在の対局は終了します。',[{label:'ホームへ',fn:goHome},{label:'続ける',secondary:true}], '⌂');$('#undoBtn').onclick=undo;$('#rotateBtn').onclick=()=>{rotated=!rotated;render()};$('#restartBtn').onclick=()=>modal('最初から始めますか？','現在の対局内容は消えます。',[{label:'最初から',fn:()=>start(current.type)},{label:'キャンセル',secondary:true}], '↻');$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'♪':'×';toast(sound?'サウンド ON':'サウンド OFF')};window.addEventListener('keydown',e=>{if(e.key==='Escape'&&current)goHome();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z')undo()});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
})();
