(()=>{'use strict';
const guides={
reversi:{title:'リバーシ',summary:'相手の石を自分の石ではさんで裏返し、最後に自分の色を多く残すゲームです。',steps:[['置く','自分の石で相手の石を縦・横・斜めにはさめる場所に石を置きます。'],['返す','はさんだ相手の石はすべて自分の色に変わります。'],['パス','置ける場所がないときは自動でパスになります。'],['勝ち','盤が埋まるか両者とも置けなくなったら終了。石が多い方の勝ちです。']],tip:'光っているマスが、今置ける場所です。'},
shogi:{title:'将棋',summary:'駒ごとの動きを使って攻め、取った相手の駒も自分の駒として使える日本の対戦ゲームです。',steps:[['動かす','自分の駒をタップして、移動先を選びます。駒ごとに動ける方向が違います。'],['取る','相手の駒がいるマスへ進むと、その駒を取れます。'],['持ち駒','取った駒は盤の外に表示され、自分の番に空いているマスへ打てます。'],['成る','相手陣地へ入る・出るときに、一部の駒は成って強くなれます。'],['勝ち','この版では相手の王を取ると勝ちです。']],tip:'駒を選ぶと、動ける場所が表示されます。'},
chess:{title:'チェス',summary:'6種類の駒を使って相手キングを追い込み、逃げ道をなくす世界定番の戦略ゲームです。',steps:[['動かす','自分の駒を選び、表示された合法手へ動かします。'],['取る','相手の駒がいるマスへ移動するとその駒を取れます。'],['チェック','キングが次に取られる状態がチェックです。必ずチェックを解消する手を選びます。'],['特殊手','キャスリング、アンパッサン、ポーンの昇格にも対応しています。'],['勝ち','チェックされたキングに逃げ道がなくなればチェックメイトで勝ちです。']],tip:'黄色の表示が選択中の駒と移動候補です。'},
mancala:{title:'マンカラ',summary:'自分側の穴にある石を1個ずつ順番に配り、ゴールに多く集めるゲームです。',steps:[['選ぶ','自分側の6つの穴から、石が入っている穴を1つ選びます。'],['配る','その穴の石を全部取り、反時計回りに1個ずつ次の穴へ落としていきます。'],['ゴール','自分の大きなゴールには石を入れますが、相手のゴールは飛ばします。'],['もう一度','最後の石が自分のゴールに入ったら、続けてもう1手できます。'],['取り込み','最後の石が自分側の空の穴に入り、その向かいに相手の石があればまとめて獲得します。'],['勝ち','片側6穴が空になったら終了。ゴールの石が多い方の勝ちです。']],tip:'石は画面上でも1個ずつ落ちていきます。'},
gomoku:{title:'五目並べ',summary:'黒と白が交互に石を置き、先に5個を一直線に並べるシンプルな対戦ゲームです。',steps:[['置く','自分の番に、空いている交点へ石を1個置きます。'],['並べる','縦・横・斜めのどれかで自分の石をつなげます。'],['勝ち','先に5個以上を一直線に並べたプレイヤーの勝ちです。']],tip:'相手の4連を止めつつ、自分の3連・4連を同時に作るのがコツです。'},
connect4:{title:'コネクト4',summary:'上からディスクを落として積み上げ、先に4個を一直線に並べるゲームです。',steps:[['落とす','置きたい列をタップすると、その列の一番下の空きへディスクが落ちます。'],['並べる','縦・横・斜めに自分の色をつなげます。'],['勝ち','先に4個を一直線に並べたプレイヤーの勝ちです。']],tip:'下から積み上がるので、相手に「次の1手で4つ」ができる場所を渡さないのが重要です。'},
ohajiki:{title:'おはじき',summary:'自分のおはじきを指で弾き、相手のおはじきを場外へ押し出すアクションゲームです。',steps:[['選ぶ','自分のおはじきに触れます。'],['引く','弾きたい方向と逆へ指を引いて力をためます。'],['離す','指を離すと、その強さでおはじきが飛びます。'],['勝ち','相手のおはじきをすべて場外へ出したプレイヤーの勝ちです。']],tip:'強く弾きすぎると自分も場外へ出やすいので、角度と力加減が大事です。'},
hasami:{title:'はさみ将棋',summary:'駒を縦横に動かし、相手の駒を両側からはさんで取るゲームです。',steps:[['動かす','自分の駒を、他の駒を飛び越えずに縦または横へ好きなだけ動かします。'],['はさむ','動かした結果、相手の駒を自分の駒で一直線にはさむと、その列の相手駒を取れます。'],['勝ち','この版では相手の駒を先に5枚取ったプレイヤーの勝ちです。']],tip:'1枚だけでなく、並んだ複数枚をまとめてはさむこともできます。'},
checkers:{title:'チェッカー',summary:'斜めに進む駒で相手を飛び越えて取り、相手の駒を減らしていくゲームです。',steps:[['進む','通常の駒は斜め前の空きマスへ1マス進みます。'],['取る','斜め隣に相手の駒がいて、その先が空いていれば飛び越えて取れます。'],['キング','奥の端まで到達した駒はキングになり、後ろ方向にも動けます。'],['勝ち','相手の駒をすべて取るか、動けなくすると勝ちです。']],tip:'取れる手があるときは、積極的に連続取りを狙いましょう。'},
dots:{title:'Dots & Boxes',summary:'点と点を線で結び、四角形を完成させて自分の陣地を増やすゲームです。',steps:[['線を引く','自分の番に、隣り合う2つの点の間へ線を1本引きます。'],['箱を取る','その線で四角形の4辺目を完成させると、その箱が自分の得点になります。'],['続ける','箱を完成させたときは、続けてもう1本線を引けます。'],['勝ち','すべての線が埋まったとき、取った箱が多い方の勝ちです。']],tip:'3辺そろった箱を相手に渡さないのが基本。終盤は連鎖が起きます。'},
sugoroku:{title:'双六',summary:'サイコロを振ってコマを進め、イベントマスを乗り越えながら先にゴールを目指します。',steps:[['振る','自分の番に「サイコロを振る」をタップします。'],['進む','出た目の数だけ自動でコマが進みます。'],['イベント','数字が増減するマスや、1回休みのマスがあります。'],['勝ち','先に最後のGOALマスへ到達したプレイヤーの勝ちです。']],tip:'運だけで遊べるので、初めての人とすぐ遊べるゲームです。'}
};
function keyFor(card){return card.dataset.game||card.dataset.extraGame}
function close(){document.querySelector('.howto-overlay')?.remove()}
function openGuide(key){const g=guides[key];if(!g)return;close();const overlay=document.createElement('div');overlay.className='howto-overlay';overlay.innerHTML=`<section class="howto-panel" role="dialog" aria-modal="true" aria-label="${g.title}の遊び方"><div class="howto-head"><div><small>HOW TO PLAY</small><h3>${g.title}</h3></div><button class="howto-close" aria-label="閉じる">×</button></div><p class="howto-summary">${g.summary}</p><div class="howto-steps">${g.steps.map((s,i)=>`<div class="howto-step"><span class="howto-num">${i+1}</span><div><strong>${s[0]}</strong><p>${s[1]}</p></div></div>`).join('')}</div><div class="howto-tip">💡 ${g.tip}</div></section>`;overlay.addEventListener('click',e=>{if(e.target===overlay||e.target.closest('.howto-close'))close()});document.body.appendChild(overlay);overlay.querySelector('.howto-close').focus()}
function install(){document.querySelectorAll('.game-card').forEach(card=>{if(card.querySelector('.howto-chip'))return;const key=keyFor(card);if(!guides[key])return;const chip=document.createElement('span');chip.className='howto-chip';chip.textContent='？ 遊び方';chip.setAttribute('role','button');chip.setAttribute('tabindex','0');chip.setAttribute('aria-label',`${guides[key].title}の遊び方`);chip.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openGuide(key)});chip.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();openGuide(key)}});card.appendChild(chip)});}
document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
window.addEventListener('DOMContentLoaded',install);
})();